In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import BitsAndBytesConfig
import accelerate

from tqdm import tqdm

In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [88]:
dataset = pd.read_csv('../data/movie.csv')
dataset.drop_duplicates(subset=['text'], inplace=True)
dataset.reset_index(drop=True, inplace=True)
dataset = dataset.iloc[:250]
dataset

text  label
0    I grew up (b. 1965) watching and loving the Th...      0
1    When I put this movie in my DVD player, and sa...      0
2    Why do people who do not know what a particula...      0
3    Even though I have great interest in Biblical ...      0
4    Im a die hard Dads Army fan and nothing will e...      1
..                                                 ...    ...
245  I was invited to an early screening of the mov...      0
246  I am so disappointed. After waiting for 3 year...      0
247  This film has gone in and out of fashion more ...      1
248  There's a part of me that would like to give t...      0
249  Japanese indie film with humor and philosophy ...      1

[250 rows x 2 columns]

In [59]:
dataset.columns

Index(['text', 'label'], dtype='object')

In [60]:
print(f'No. of samples: {len(dataset)}')
print(f'No. of features: {dataset.drop(columns="label").shape[1]}')
print(f'Features: {dataset.drop(columns="label").columns.to_list()}')
print(f'No. of classes: {len(dataset["label"].unique())}')
print(f'Classes: {dataset["label"].unique()}')

No. of samples: 250
No. of features: 1
Features: ['text']
No. of classes: 2
Classes: [0 1]


In [61]:
X_train, X_test, y_train, y_test = train_test_split(dataset.drop(columns=['label']), dataset['label'], test_size=.2)

X_train = X_train.astype(str)
X_test = X_test.astype(str)
y_train = y_train.astype(int)
y_test = y_test.astype(int)

In [62]:
y_train = y_train.astype(int).to_numpy()
y_test = y_test.astype(int).to_numpy()

In [3]:
model_id = "meta-llama/Meta-Llama-3-8B-Instruct"

In [4]:
quantization_config = BitsAndBytesConfig(
    load_in_8bit=True,
    bnb_8bit_use_double_quant=True,
    bnb_8bit_quant_type='nf8',  # Can be 'nf4' or 'fp4'
    bnb_8bit_compute_dtype=torch.bfloat16  # Adjust compute type if needed
)

In [5]:
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    device_map='auto',
    quantization_config=quantization_config,
    output_hidden_states=True,
)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [6]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear8bitLt(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear8bitLt(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear8bitLt(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear8bitLt(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear8bitLt(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )


In [7]:
def get_model_size(model):
    total_params = sum(p.numel() for p in model.parameters())
    total_size_bytes = total_params * 2
    total_size_gb = total_size_bytes / (1024 ** 3)
    print(f"Model size: {total_size_gb:.2f} GB")

get_model_size(model)

Model size: 14.96 GB


In [8]:
model.device

device(type='cuda', index=0)

In [63]:
def prompt_llm(prompt, max_tokens=20):
    messages = [
        {"role": "system", "content": "You are a sentiment predicting chatbot that predicts the sentiment of a movie review as positive or negative."},
        {"role": "user", "content": prompt},
    ]

    input_ids = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        return_tensors="pt"
    ).to(model.device)

    terminators = [
        tokenizer.eos_token_id,
        tokenizer.convert_tokens_to_ids("<|eot_id|>")
    ]

    with torch.no_grad():
        outputs = model.generate(
            input_ids,
            max_new_tokens=max_tokens,
            eos_token_id=terminators,
            pad_token_id=tokenizer.eos_token_id,
            do_sample=True,
            temperature=0.6,
            top_p=0.9,
            output_hidden_states=True,  # Enable hidden states
            return_dict_in_generate=True  # Ensure hidden states are included in the output
        )

    generated_tokens = outputs.sequences[0][input_ids.shape[-1]:]
    
    hidden_states = outputs.hidden_states  # Shape: (num_layers, batch_size, seq_len, hidden_size)
    num_layers = len(hidden_states)
    # return hidden_states
    
    # Last Token Embedding
    first_layer_hidden_state = hidden_states[-1][0][:, -1, :].squeeze().cpu().numpy()
    middle_layer_hidden_state = hidden_states[-1][num_layers // 2][:, -1, :].squeeze().cpu().numpy()
    last_layer_hidden_state = hidden_states[-1][-1][:, -1, :].squeeze().cpu().numpy()

    response_text = tokenizer.decode(generated_tokens, skip_special_tokens=True)
    del input_ids
    torch.cuda.empty_cache()

    return {
        'prompt': prompt,
        'response': response_text,
        'first_layer_embedding': first_layer_hidden_state,  # Embedding from the first layer
        'middle_layer_embedding': middle_layer_hidden_state,  # Embedding from the middle layer
        'last_layer_embedding': last_layer_hidden_state  # Embedding from the last layer
    }

In [64]:
dataset.iloc[111]

text     I used to write comments at IMDb, but I don't ...
label                                                    1
Name: 111, dtype: object

In [65]:
prompt_llm(f'What is the sentiment for this review: Just output Postive or Negative?\n"{dataset.iloc[111]["text"]}"', max_tokens=40)['response']

'Positive'

In [ ]:
for x in X_train.iterrows():
    prompt = f"{', '.join([': '.join(i) for i in zip(x[1].index, x[1].values)])}"
    output = prompt_llm(prompt)
    print(output)
    print(len(output))
    print(len(output[0]))
    print(output[0][0].shape)
    break

In [66]:
train_embeddings_first = []
train_embeddings_middle = []
train_embeddings_last = []
train_prompts = []
train_responses = []

for x in tqdm(X_train.iterrows(), total=len(X_train), desc='Generating embeddings for training data'):
    prompt = f'What is the sentiment for this review: Just output Postive or Negative?\n"{x[1]["text"]}"'
    output = prompt_llm(prompt)
    train_prompts.append(output['prompt'])
    train_responses.append(output['response'])
    train_embeddings_first.append(output['first_layer_embedding'])
    train_embeddings_middle.append(output['middle_layer_embedding'])
    train_embeddings_last.append(output['last_layer_embedding'])

train_embeddings_first = np.array(train_embeddings_first)
train_embeddings_middle = np.array(train_embeddings_middle)
train_embeddings_last = np.array(train_embeddings_last)

Generating embeddings for training data: 100%|██████████| 200/200 [01:38<00:00,  2.03it/s]


In [67]:
test_embeddings_first = []
test_embeddings_middle = []
test_embeddings_last = []
test_prompts = []
test_responses = []

for x in tqdm(X_test.iterrows(), total=len(X_test), desc='Generating embeddings for testing data'):
    prompt = f'What is the sentiment for this review: Just output Postive or Negative?\n"{x[1]["text"]}"'
    output = prompt_llm(prompt)
    test_prompts.append(output['prompt'])
    test_responses.append(output['response'])
    test_embeddings_first.append(output['first_layer_embedding'])
    test_embeddings_middle.append(output['middle_layer_embedding'])
    test_embeddings_last.append(output['last_layer_embedding'])

test_embeddings_first = np.array(test_embeddings_first)
test_embeddings_middle = np.array(test_embeddings_middle)
test_embeddings_last = np.array(test_embeddings_last)

Generating embeddings for testing data: 100%|██████████| 50/50 [00:25<00:00,  1.95it/s]


In [81]:
cl_model_first = LogisticRegression(max_iter=100)
cl_model_middle = LogisticRegression(max_iter=100)
cl_model_last = LogisticRegression(max_iter=100)

# cl_model_first = RandomForestClassifier()
# cl_model_middle = RandomForestClassifier()
# cl_model_last = RandomForestClassifier()

In [51]:
# y_train = y_train.to_numpy(dtype='object')
# y_test = y_test.to_numpy(dtype='object')

In [82]:
cl_model_first.fit(train_embeddings_first, y_train)
cl_model_middle.fit(train_embeddings_middle, y_train)
cl_model_last.fit(train_embeddings_last, y_train)

LogisticRegression()

In [83]:
y_pred_train_first = cl_model_first.predict(train_embeddings_first)
y_pred_train_middle = cl_model_middle.predict(train_embeddings_middle)
y_pred_train_last = cl_model_last.predict(train_embeddings_last)

y_train, y_pred_train_first, y_pred_train_middle, y_pred_train_last

(array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
        1, 0]),
 array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
        0, 1, 1, 0, 0,

In [84]:
print(f'First Layer Accuracy: {accuracy_score(y_train, y_pred_train_first)}')
print(f'Middle Layer Accuracy: {accuracy_score(y_train, y_pred_train_middle)}')
print(f'Last Layer Accuracy: {accuracy_score(y_train, y_pred_train_last)}')

print(f'First Layer F1 Score: {f1_score(y_train, y_pred_train_first, average="weighted")}')
print(f'Middle Layer F1 Score: {f1_score(y_train, y_pred_train_middle, average="weighted")}')
print(f'Last Layer F1 Score: {f1_score(y_train, y_pred_train_last, average="weighted")}')

First Layer Accuracy: 0.955
Middle Layer Accuracy: 0.955
Last Layer Accuracy: 1.0
First Layer F1 Score: 0.9549943748593716
Middle Layer F1 Score: 0.9549943748593716
Last Layer F1 Score: 1.0


In [85]:
y_pred_test_first = cl_model_first.predict(test_embeddings_first)
y_pred_test_middle = cl_model_middle.predict(test_embeddings_middle)
y_pred_test_last = cl_model_last.predict(test_embeddings_last)

y_test, y_pred_test_first, y_pred_test_middle, y_pred_test_last

(array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 0, 1]),
 array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1]),
 array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1]),
 array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 1, 0, 1, 0, 1]))

In [86]:
print(f'First Layer Accuracy: {accuracy_score(y_test, y_pred_test_first)}')
print(f'Middle Layer Accuracy: {accuracy_score(y_test, y_pred_test_middle)}')
print(f'Last Layer Accuracy: {accuracy_score(y_test, y_pred_test_last)}')

print(f'First Layer F1 Score: {f1_score(y_test, y_pred_test_first, average="weighted")}')
print(f'Middle Layer F1 Score: {f1_score(y_test, y_pred_test_middle, average="weighted")}')
print(f'Last Layer F1 Score: {f1_score(y_test, y_pred_test_last, average="weighted")}')

First Layer Accuracy: 0.88
Middle Layer Accuracy: 0.88
Last Layer Accuracy: 0.9
First Layer F1 Score: 0.8787775891341256
Middle Layer F1 Score: 0.8787775891341256
Last Layer F1 Score: 0.8995376208490964
